name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build-and-test-ros:
    name: Build and test ROS nodes
    runs-on: ubuntu-latest
    container:
      image: ros:humble
    steps:
      - name: Check if branch is master
        id: check_branch
        run: |
          echo "branch_name=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Skip job if not master branch
        if: ${{ env.branch_name != 'master' && github.event_name == 'schedule' }}
        run: echo "Skipping daily run because the branch is not master."
        
      - uses: actions/checkout@v4
        with:
          # ROS expects the sources in a workspace to be in `src` - we can use the checkout folder as the workspace folder
          path: src
      - name: Install Prerequisites
        run: |
          bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
          apt-get update && apt-get upgrade -y && apt-get install ros-dev-tools -y && rosdep update; \
          rosdep install --from-paths src --ignore-src -y'
      - name: Build Workspace
        run: |
          bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
          colcon build'
      - name: Run Tests
        run: |
          bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
          colcon test; \
          colcon test-result --verbose'

  # simplify GH settings: have one single build to be required
  build-results:
    name: Final Results
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - build-and-test-ros
    steps:
      - name: "check for failed builds"
        run: |
          cat <<EOF | jq -e 'unique | all(. == "success")'
          ${{ toJson(needs.*.result) }}
          EOF